### ISSUE TITLE
poly-org mode slows down insertions to large org files

### ISSUE THREAD

**Issue by vapniks** [polymode/poly-org#10]
I have several large org files (>12000 lines) for keeping notes, and for which I do not need `poly-org-mode` (I do need it for other org files).
When I try inserting text in one of the large files with `poly-org-mode` running it is extremely slow (approx 1 second lag between each character insertion). 
I cannot find a way to easily turn `poly-org-mode` off; with most other minor modes you can turn them off by entering the mode command with a negative argument, but that doesn't work with `poly-org-mode`.

**Comment by vspinu** [comment]
So it's a large file with no code chunks? Then yes, I can see some slow down. I was fearing this use case. Will have a look asap.

**Comment by vspinu** [comment]
Should be fixed in polymode master.

**Comment by vapniks** [comment]
Great, thanks. What about the problem of not being able to turn `poly-org-mode` off? Shall I raise another issue for this, or have I overlooked something?
