### ISSUE TITLE
Poly-org and org-capture

### ISSUE THREAD

**Issue by yantar92** [polymode/poly-org#2]
Buffer narrowing in org-capture is not working with poly-org-mode in the capture buffer.
Moreover, the `C-c C-c` and `C-c C-k` are not working.

**Comment by yantar92** [comment]
1. emacs -Q
2. Create the following org file in ~/tmp/inbox.org:

````

* Test preexising heading

* And another heading

````
3. Load the following config. The org capture templates variable should point to the newly created file (just in case if you did not make a file in ~/tmp/inbox.org)

````
  (require 'package)
  (setq package-archives '(("MELPA" . "https://melpa.org/packages/") ("ELPA" . "http://tromey.com/elpa/") ("gnu" . "http://elpa.gnu.org/packages/") ("org" . "http://orgmode.org/elpa/"))
	load-prefer-newer t
	package-user-dir "~/.emacs.d/elpa/"
	package--init-file-ensured t
	package-enable-at-startup nil)
  (unless (file-directory-p package-user-dir)
    (make-directory package-user-dir t))
  (setq load-path (append '("~/.emacs.d/site-lisp/") load-path))
  (setq load-path (append (directory-files "~/.emacs.d/site-lisp/" t "^[^.]" t) load-path))
  (setq load-path (append (directory-files package-user-dir t "^[^.]" t) load-path))
  (add-hook 'after-init-hook #'package-initialize)
  (package-initialize 'NO-ACTIVATE)
;; Package management & configuration:2 ends here

;; [[id:4c0a06f9-9e69-4ead-b570-e3143fa0d61d][Package management & configuration:3]]
(require 'use-package)
(use-package diminish :ensure t)
(require 'bind-key)
;; Package management & configuration:3 ends here

(use-package polymode
  :ensure t
  :init
  (use-package poly-org
    :ensure t))

(setq org-capture-templates
      '(("n" "TODO item" entry (file "~/tmp/inbox.org") ;; <<--- capture buffer
	 "* TODO %? %a\n:PROPERTIES:\n:CREATED: %U\n:END:\n" :clock-in t :clock-resume t)))
````
4. `M-x` `org-capture` `n` 
5. Take a look at the top row of the capture buffer. It contains the line "Capture buffer. Finish C-c C-c, abort C-c C-k.". The line disappears after a short while. 
Moreover, the capture buffer is narrowed to the new capture entry by default. The narrowing is not there any more as well.

**Comment by dankessler** [comment]
I'm experiencing this also. This seems like a more general `polymode` issue that it's not possible to switch to indirect buffers; I've opened an issue on `polymode` regarding this https://github.com/polymode/polymode/issues/225

**Comment by vspinu** [comment]
Should be fixed now. Thanks for all the input.
