### ISSUE TITLE
Poly-org sends entire org file to python

### ISSUE THREAD

**Issue by zhenhua-wang** [polymode/poly-org#24]
Hi, 

Instead of sending the specific codes in a code block, "C-c C-c" sends everything (including notes, results, headlines, etc.) in an org file to Python repl. Could you be able to help me with this issue?

But in an R code block, poly-org works as expected. 

Thanks!

**Comment by zhenhua-wang** [comment]
Here is an example
<img width="430" alt="Screen Shot 2020-03-13 at 3 07 38 PM" src="https://user-images.githubusercontent.com/11971417/76652185-6b3fae00-653c-11ea-9458-17560cb4e1ce.png">

Instead of just sending codes, it also sends headlines. Following is the error generated
<img width="711" alt="Screen Shot 2020-03-13 at 3 09 07 PM" src="https://user-images.githubusercontent.com/11971417/76652366-d25d6280-653c-11ea-89cb-3da9471e9d5a.png">

**Comment by mafes1** [comment]
The same problem is happening to me now. Was this issue solved?

**Comment by zhenhua-wang** [comment]
> The same problem is happening to me now. Was this issue solved?

`C-c C-c` is binded to `python-shell-send-buffer`, which would send the entire buffer including org text. You probably want to call `python-shell-send-region` or `python-shell-send-statement` instead. I stop using poly-org now, so I cannot test this.

**Comment by mafes1** [comment]
> > The same problem is happening to me now. Was this issue solved?
> 
> `C-c C-c` is binded to `python-shell-send-buffer`, which would send the entire buffer including org text. You probably want to call `python-shell-send-region` or `python-shell-send-statement` instead. I stop using poly-org now, so I cannot test this.

You're right. Thank you!
