### ISSUE TITLE
Polymode is triggered in #+Latex_Header org document

### ISSUE THREAD

**Issue by frederic-santos** [polymode/poly-org#35]
Hi,

It seems that a recent change introduced an issue relative to the headers of an org document. Consider the following header:
![bug_pm](https://user-images.githubusercontent.com/33752346/151962791-13d4be1d-9e55-4af9-b226-ee4c3bf93cea.png)

As you can see, when opening the document, polymode triggers latex-mode starting from line 13, to the end of the document, which is not what we want. (In particular, this prevents the correct use of org mode for the whole document; see for instance line 18 which is still in latex-mode.)

Looks like certain expressions are treated differently since a recent update --- the exact same header did not raise any problem with versions of polymode around late December 2021.

**Comment by vspinu** [comment]
Hmm. I see that the `\begin` head matcher is anchored to the bol [here](https://github.com/polymode/poly-org/blob/b4874ff587189dea8fad56be3b6c34e450a68b68/poly-org.el#L76) So you case should not have been matched. 

Could you please provide a txt version of your example, so that I won't have to re-type all of that?

**Comment by frederic-santos** [comment]
Thanks!
Here is the text version:
```
#+TITLE: Title
#+AUTHOR: Author
#+DATE: \today
#+STARTUP: showall noindent
#+LATEX_HEADER: \usepackage{a4wide}
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{mdframed}
#+LATEX_HEADER: \usepackage{fancyvrb}
#+LATEX_HEADER: \usemintedstyle{friendly}
#+LATEX_HEADER: \mdfdefinestyle{mystyle}{linecolor=gray!30,backgroundcolor=gray!30}
#+LATEX_HEADER: \BeforeBeginEnvironment{minted}{%
#+LATEX_HEADER: \begin{mdframed}[style=mystyle]}
#+LATEX_HEADER: \AfterEndEnvironment{minted}{%
#+LATEX_HEADER: \end{mdframed}}
#+LANGUAGE: fr

* A first org header
```
