### ISSUE TITLE
'org-element-at-point’ cannot be used in non-Org buffer

### ISSUE THREAD

**Issue by ploedige** [polymode/poly-org#49]
When using poly-org I get a lot of warnings

> ⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer config.org[emacs-lisp]> (emacs-lisp-mode)
> ⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer config.org[emacs-lisp]> (emacs-lisp-mode)
> ⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer config.org[emacs-lisp]> (emacs-lisp-mode)
> ⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer config.org[emacs-lisp]> (emacs-lisp-mode)
> ⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer config.org[emacs-lisp]> (emacs-lisp-mode)
>...

Note: `config.org`is the file I am working on

These are very annoying.
For reference. I am using Doom Emacs and the following configuration

<details>
<summary> packages.el </summary>

```emacs-lisp
(package! polymode)
(package! poly-org)
```
</details>
<details>
<summary> config.el </summary>

```emacs-lisp
(after! org
  (require 'poly-org))
```
</details>

Any help fixing/avoiding these warnings would be greatly appreciated

**Comment by 0ax-christin** [comment]
I have the exact same issue, seems to be that the org document is being opened in emacs-lisp mode which is causing the whole glitch. Re-enabling org-mode manually on the buffer seems to fix it, but otherwise I have no idea how to fix the issue.
For now I have just commented out polymode.

**Comment by maikol-solis** [comment]
I have the same issue. It's very annoying. I think the culprit is org-mode 9.7, since I haven't had this behavior before with 9.6.

**Comment by maikol-solis** [comment]
I pinned org to https://github.com/emacs-straight/org-mode/commits/release_9.6.30/ as a temporary workaround.

**Comment by maikol-solis** [comment]
In doom-emacs I am having this debug info after activate poly-org with 9.7. 



```elisp
    Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
    org-eldoc-get-src-lang()
    #<subr org-eldoc-documentation-function>(#f(compiled-function (string &rest plist) #<bytecode -0x1a7bc63dbd6d722>))
    apply(#<subr org-eldoc-documentation-function> #f(compiled-function (string &rest plist) #<bytecode -0x1a7bc63dbd6d722>))
    org-eldoc-documentation-function(#f(compiled-function (string &rest plist) #<bytecode -0x1a7bc63dbd6d722>))
    #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_15>(org-eldoc-documentation-function)
    eldoc-documentation-default()
    eldoc--invoke-strategy(nil)
    eldoc-print-current-symbol-info()
    #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_11>()
    apply(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_11> nil)
    timer-event-handler([t 0 0 500000 nil #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_11> nil idle 0 nil])
```

**Comment by mcmillanbb** [comment]
I had the same problem, partially fixed by disabling org-indent-mode. It calls org-element-at-point on every line, and then fails, giving the long list of errors.

Org-mode frequently calls org-element-at-point, which now has a check to ensure that the major mode is derived from org. 
On the other hand, poly-modes are not major modes, rather minor modes that glue together several buffers, each open in their respective major modes. The src block mode will not generally be org-derived, hence the error.

**Comment by mcmillanbb** [comment]
I made a fork to fix this issue. If anyone would like to try it, the usage is as follows (for example, to use elisp, latex and python source blocks):
```
(use-package poly-org
  :autoload poly-org-enable-modes
  :init (poly-org-enable-modes '("elisp" "latex" "python")))
```
The function poly-org-enable-modes takes a list of keys as org would associate to a mode using org-src-lang-modes and for each asociated mode creates an inherited mode that will also be compatible with org. This new mode is then used as the inner mode for the corresponding src blocks.

**Comment by vspinu** [comment]
Sorry folks. I was out of maintanence for 2 years for personal reasons.  

Standard way to deal with such problems is to execute the problematic function in its own host buffer. For example:

```el
(pm-around-advice 'org-element-at-point #'polymode-with-current-base-buffer )
;; can advice multiple functions at once
;; (pm-around-advice '(fn1 fn2 ...) #'polymode-with-current-base-buffer)
```
I still have old org 9.6.15 on my machine so could not test. If any of you is still on the wire, could you please check on your side?

**Comment by mcmillanbb** [comment]
First of all, welcome back!

I just did a quick test, advising org-element-at-point does seem to work. This would of course be a much more elegant solution.

My one concern about trying that was performance, since org calls org-element-at-point very frequently. But if the advice doesn't add much overhead, then it shouldn't be a problem.

**Comment by vspinu** [comment]
Thanks! It should be very snappy and it only does the magic in polymode buffers. So plain org-mode functionality won't be affected at all, this is just `with-current-buffer base` wrapping the original function with some extra points sync across the buffers.

**Comment by maikol-solis** [comment]
Thanks @vspinu. It worked for me.
