### ISSUE TITLE
polyOrg and :session

### ISSUE THREAD

**Issue by fkgruber** [polymode/poly-org#8]
Hi
I noticed that poly org seems to be ignoring the :session assign to the block.

Suppose I'm running multiple R session and I specify the code block to use a specific session (or I specify it for the buffer in the header). Then I would think poly org would automatically use the correct session to send the code to. Currently it ask you the first time which session to use and from then on it uses that session. 

It seems to me that it would make sense if the :session header should define which R session to use.

thanks
FKG

**Comment by vspinu** [comment]
Indeed. All inner modes share same indirect buffer, so it will be connected to one inferior. In principle one can create separate inner modes per session but it would complicate things a bit. 

Easier would be to install a hook which would automatically assign a session when you move to an R chunk.

**Comment by vspinu** [comment]
I have implemented the above mentioned idea. it's not perfect, as it will not detect org session if you start it from inside an R block. If you always start your or sessions from outside of R blocks everything should be fine. 

The full proof solutions should be implemented on the ESS side once emacs-ess/ESS#914 is in.
