### ISSUE TITLE
please don't add poly-org-mode to auto-mode-alist by default

### ISSUE THREAD

**Issue by vapniks** [polymode/poly-org#9]
I have some very large `org-mode` files which I use frequently and `poly-org-mode` really slows them down; when I try editing a table there is a huge lag if `poly-org-mode` is active.
I would rather it was not loaded by default.

**Comment by vspinu** [comment]
Just don't install, or don't load poly-org or overwrite the alist. Polymodes are just like emacs modes which all load their mode in auto-list for the majority convenience. The assumption is that if you use poly-org, you want it. 

If there are speed issues, please report as a separate issue on the main repor and I will have a look. There have been big speed improvements in the past month. So make sure you are using the most recent poly-org.

**Comment by vapniks** [comment]
I use `poly-org-mode` occasionally for R or stata analysis, but have many other org-mode files where I don't need it. Most minor modes are optional; you can turn them on or off. There seems to be no way to turn `poly-org-mode` off.

**Comment by vspinu** [comment]
That's a bug. In principle one should be able to  `M-x org-mode` or `M-x poly-org-mode` but it currently doesn't work. I have opened polymode/polymode#223 for this.

`poly-org-mode` is designed as a major mode. Using it as a minor mode in hooks might lead to unexpected results in some corner cases such like when org is used as an innermode.

**Comment by vspinu** [comment]
> In principle one should be able to M-x org-mode or M-x poly-org-mode

Both of which work now. Thanks for pushing. This one was on my mind forever :)

**Comment by vapniks** [comment]
great, thankyou :)
